### ISSUE TITLE
Mismatch of the code example with "Types of branch"

### ISSUE THREAD

**Issue by daydayup40** [hardenedlinux/harbian-qa#13]
The analysis in the following link is very good!
https://github.com/hardenedlinux/harbian-qa/tree/master/syzkaller/kstat_demo#types-of-branch
But when I follow into the code example, I think that there may be some mismatch with the code and what you mean. Right?
If I misunderstand something, please let me know.

**Comment by Bins94** [comment]
Could you point out which link is mismatch?

**Comment by daydayup40** [comment]
For the first type of branch, the example link https://elixir.bootlin.com/linux/v4.20/source/net/ipv4/tcp.c#L1188 is not pointed to msg_flags.
For the second type of branch, the example link https://elixir.bootlin.com/linux/v4.20/source/net/ipv4/tcp.c#L1189 is not pointed to sk_state. And https://elixir.bootlin.com/linux/v4.20/source/net/ipv4/tcp.c#L1231 is not pointed to repair_queue.
For the third type of branch, I can't get which local variable is changed by which line form the link https://elixir.bootlin.com/linux/v4.20/source/net/ipv4/tcp.c#L1346 and https://elixir.bootlin.com/linux/v4.20/source/net/ipv4/tcp.c#L1330.
Thanks for your help!

**Comment by Bins94** [comment]
https://elixir.bootlin.com/linux/v4.20/source/net/ipv4/tcp.c#L1188 is determined by msg_flags, Right? 
It seems there is no mismatch.

**Comment by daydayup40** [comment]
Sorry. It's due to my 360 browser. Its results are not correct. Chrome's results are correct. Thanks!
