### ISSUE TITLE
Did you only compare the efficient of customize syz-hub witht original syz-hub?

### ISSUE THREAD

**Issue by daydayup40** [hardenedlinux/harbian-qa#17]
@Bins94 
The multi-policy fuzzer is a great job! (https://github.com/hardenedlinux/harbian-qa/tree/master/syzkaller/multi_policy#a-test-for-tcpipv6)
1. Did you only compare the efficiency of customized syz-hub with original syz-hub?
2. Did you run different syzkaller in docker and connect via syz-hub?
Thanks for your help!

**Comment by Bins94** [comment]
Hi, 
1. Do you mean: if there is any improvement of running several original syz-manager with customized syz-hub?  Still testing. I ran original syz-hub with multi-policy syz-manager( include customized syz-manager). It show a terrible performance. So, we have this customized syz-hub.
2. I never run syzkaller in docker. I don't think it will be very hard connecting to syz-hub if you have already ran a syzkaller in docker. If you finish trying this. Welcome to contribute your documentation to harbian-qa.

**Comment by daydayup40** [comment]
Thanks!
1. Yes. Looking forward to your experiment result.
2. Ok.
