### ISSUE TITLE
survey.md

### ISSUE THREAD

**Issue by daydayup40** [hardenedlinux/harbian-qa#26]
Hi!

The last sentence in https://github.com/hardenedlinux/harbian-qa/blob/master/survey.md refer to a 404 link: https://github.com/hardenedlinux/harbian-qa/blob/master

**Comment by Bins94** [comment]
Hi, 
I am writing that document. I will add the link after i finished it.
Thank you!

**Comment by daydayup40** [comment]
Thanks!
